### ISSUE TITLE
Support within_polygon

### ISSUE THREAD

**Issue by timwis** [timwis/soda-geoservices#7]
SODA2 supports `within_polygon()` ([docs](https://dev.socrata.com/docs/functions/within_polygon.html)). Example query:

`$where=within_polygon(location, 'MULTIPOLYGON (((-87.637714 41.887275, -87.613681 41.886892, -87.625526 41.871555, -87.637714 41.887275)))')`

Should this use Geoservice's `Multipoint` or `Polygon` query?

Example `Multipoint`:

``` json
{
  "points" : [[-97.06138,32.837],[-97.06133,32.836],[-97.06124,32.834],[-97.06127,32.832]],
  "spatialReference" : {"wkid" : 4326}
}
```

Example `Polygon`:

``` json
{
  "rings" : [[[-97.06138,32.837],[-97.06133,32.836],[-97.06124,32.834],[-97.06127,32.832],
              [-97.06138,32.837]],[[-97.06326,32.759],[-97.06298,32.755],[-97.06153,32.749],
              [-97.06326,32.759]]],
  "spatialReference" : {"wkid" : 4326}
}
```

Aesthetically, it looks more like `Multipoint`, but considering it's standard WKT (MULTIPOLYGON), `Polygon` may be the direct translation.

**Comment by timwis** [comment]
@ajturner, any suggestions?

**Comment by timwis** [comment]
@chelm may know too?

**Comment by ajturner** [comment]
I'm not entirely sure - but by nomenclature I would presume that `POLYGON` is the right query, and the SODA Doc example only has a single polygon of the multipolygon. Kind of like a one-element array.

**Comment by chelm** [comment]
Polygon!

**Comment by timwis** [comment]
Okay, thanks guys!
